services:
  - type: web
    name: school-bot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: 8382795223:AAH9T3qbYiSOJkt__bsiMgXi8bOd7gjpHuc
        sync: false
